apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email-app
  template:
    metadata:
      labels:
        app: email-app
    spec:
      containers:
        - name: email-app
          image: nedumacr.azurecr.io/nedumpythonapp:80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
