apiVersion: v1
kind: Service
metadata:
  name: email-app-service
  labels:
    app: email-app
spec:
  selector:
    app: email-app
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
